@set _OPTIONS= 

@rem @set _OPTIONS=%_OPTIONS% -DMAKE_PYTHON_WRAPPER=ON -DPYTHON_VERSION=%_PYTHON_VERSION% -DPYTHON_EXECUTABLE=%_PYTHON% -DPYTHON_INCLUDE_DIRS="%_PYTHON_INCLUDE_DIR%" -DPYTHON_LIBRARIES="%_PYTHON_LIB%" -DBOOST_ROOT="%_BOOST_SRC_DIR%" -DBOOST_LIBRARYDIR="%_BOOST_LIB_DIR%"
@set _OPTIONS=%_OPTIONS% -DMAKE_PYTHON_WRAPPER=ON -DBOOST_ROOT="%_BOOST_SRC_DIR%" -D_BOOST_PYTHON_LIB=%_BOOST_PYTHON_LIB% -D_BOOST_NUMPY_LIB=$%_BOOST_NUMPY_LIB%

@rem @set _OPTIONS=%_OPTIONS% -DPYTHON_DEBUG_OUTPUT=ON
@set _OPTIONS=%_OPTIONS% -DPYTHON_DEBUG_OUTPUT=OFF